---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
# Регрессионный анализ социально-экономических процессов, 2025 -- 2026
 
### Обозначения
 
`r  shiny::icon("scroll")` -- презентация / конспект занятия / семинарский листочек
 
`r  shiny::icon("readme")` -- Reading
 
`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)
 
`r  shiny::icon("pencil")` -- задание 
 
## Занятие 1
 
Тема: О чем курс и каковы правила игры? Повторение: условное мат. ожидание; парная линейная регрессия
  
`r  shiny::icon("scroll")` <a href="css_reg_intro.pdf" title=>Презентация-введение</a> 

`r  shiny::icon("scroll")` <a href="css_reg_notes_1.pdf" title=>Конспект</a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar1_2025.pdf" title=>Семинарский лист 1</a> 

<u>Домашнее задание</u>: 
 
Просмотреть следующие статьи (особенно исследовательский дизайн, кроме того, как используется ATE): 

`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/ri6jodHqYpQxCw" title=>Mayer, 2011</a>; 

`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/egohYd4tpMy_gg" title=>Pianzola et al., 2019</a>
 
## Занятие 2
 
Тема: множественная линейная регрессия: спецификация, оценивание параметров, условия Гаусса-Маркова

`r  shiny::icon("scroll")` <a href="reg_notes_2_.pdf" title=>Конспект</a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar2_2025.pdf" title=>Семинарский лист 2</a> 

`r  shiny::icon("desktop")` <a href="css_reg_lab1.ipynb" title=>Практикум 1</a> 

`r  shiny::icon("desktop")` <a href="lab1.dta" title=>lab1.dta</a> 

<u>Домашнее задание</u>: `r  shiny::icon("scroll")` <a href="css_reg_hw2.pdf" title=>Задачи для тренировки</a> 

`r  shiny::icon("scroll")` <a href="css_reg_hw2_solution.pdf" title=>Решение задач</a> 

## Занятие 3 

Тема: спецификация множественной линейной модели,  модели с переменными взаимодействия 

`r  shiny::icon("scroll")` <a href="interactions.pdf" title=>Презентация. Переменные взаимодействия</a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar3.pdf" title=>Семинарский лист 3</a> 

`r  shiny::icon("scroll")` <a href="interactions_solution.pdf" title=>Решение семинарского листка</a> 

Литература по теме:
 
`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/XhNnotShTyC8dw" title=> Brambor et al.</a>
 
`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/ufuj_2Ks2FglpQ" title=> Franzese, Kam, pp. 19 - 39 </a>

<u>Домашнее задание (сдаваемое обязательное)</u>: `r  shiny::icon("scroll")` <a href="css_reg_hw1_submit.pdf" title=>Условие ДЗ1 (сдаваемое)</a> 

## Занятие 4 

Тема: модели с переменными взаимодействия, модель разность разностей  

`r  shiny::icon("desktop")` <a href="reg_lab2_UPD.ipynb" title=>Практикум 2</a> 

`r  shiny::icon("desktop")` <a href="lab1.dta" title=>lab1.dta</a> 

`r  shiny::icon("scroll")` <a href="DiD_lecture.pdf" title=>Презентация. DiD </a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar4.pdf" title=>Семинарский лист 4</a>

`r  shiny::icon("desktop")` <a href="reg_lab3_2025.ipynb" title=>Практикум 3</a> 

`r  shiny::icon("desktop")` <a href="DiDdata.dta" title=>DiDdata.dta</a>

## Занятие 5

Тема: проверочная работа

`r  shiny::icon("scroll")` <a href="css_reg_test1_1_2025.pdf" title=>Вариант 1</a> 

`r  shiny::icon("scroll")` <a href="css_reg_test1_2_2025.pdf" title=>Вариант 2</a>

## Занятие 6

Тема: мультиколлинеарность; МГК 

`r  shiny::icon("scroll")` <a href="css_reg_lecture_multicollinearity.pdf" title=>Презентация. Мультиколлинеарность. МГК</a> 

`r  shiny::icon("scroll")` <a href="reg_seminar5.pdf" title=>Семинарский лист 5 </a>

`r  shiny::icon("desktop")` <a href="reg_lab4__2025.ipynb" title=>Практикум 4</a> 

## Занятие 7

Тема: гетероскедастичность, нетипичные наблюдения 

`r  shiny::icon("scroll")` <a href="heteroskedasticity_lecture.pdf" title=>Презентация. Гетероскедастичность</a> 

`r  shiny::icon("scroll")` <a href="reg_seminar6.pdf" title=>Семинарский лист 6 </a>

`r  shiny::icon("desktop")` <a href="reg_lab5__2025.ipynb" title=>Практикум 5</a> 

## Занятие 8

Тема: повторение, применение линейных регрессионных моделей в исследованиях

`r  shiny::icon("scroll")` <a href="css_reg_research.pdf" title=>Презентация. Применение в исследованиях</a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar7.pdf" title=>Семинарский лист 7 </a>

## Занятие 9

Тема: меры качества линейной регрессионной модели, кросс-валидация, сравнение альтернативных спецификаций

`r  shiny::icon("scroll")` <a href="css_reg_class8.pdf" title=>Презентация. Меры качества</a> 

`r  shiny::icon("desktop")` <a href="css_reg_lab_6.ipynb" title=>Практикум 6</a> 

`r  shiny::icon("desktop")` <a href="data_ridge.dta" title=>data_ridge.dta</a> 

## Занятие 10

Тема: модели с бинарным откликом

`r  shiny::icon("scroll")` <a href="css_reg_BCM.pdf" title=>Презентация. Модели с бинарным откликом</a> 

`r  shiny::icon("scroll")` <a href="css_reg_seminar8.pdf" title=>Семинарский лист 8 </a>

`r  shiny::icon("desktop")` <a href="css_reg_lab_7.ipynb" title=>Практикум 7</a> 

`r  shiny::icon("desktop")` <a href="lab_logit.dta" title=>lab_logit.dta</a> 

## Занятие 11

Тема: модели с порядковым откликом

`r  shiny::icon("scroll")` <a href="css_reg_class10.pdf" title=>Презентация. Модели с порядковым откликом</a> 

`r  shiny::icon("desktop")` <a href="css_reg_lab8.ipynb" title=>Практикум 8</a> 


 